export const REMOVE_USER = 'REMOVE_USER';
export const CHECK_USER = 'CHECK_USER';
export const GET_ITEMS = 'GET_ITEMS';
export const REMOVE_ITEM_FROM_BASKET = 'REMOVE_ITEM_FROM_BASKET';
export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const SET_CATEGORY_PERANT = 'SET_CATEGORY_PERANT';
export const REMOVE_ALL_FROM_BASKET = 'REMOVE_ALL_FROM_BASKET';
